{
 "title": "Notification Service",
 "description": "Application metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Business", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total SMS sent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "smsCount" }
   ]
  },
  {
   "title": "Total Push To Webhooks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "pushToWebhookCounter" }
   ]
  },
  {
   "title": "Total Push To Webhook Failures",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "pushToWebhookFailureCounter" }
   ]
  },
  {
   "title": "Pending Notifications",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "notificationPendingCount" }
   ]
  },
  {
   "title": "Total Emails sent",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "emailCount" }
   ]
  },
  {
   "title": "Total Emails Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "emailFailureCount" }
   ]
  },
  {
   "title": "Notification Success Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "notificationSuccessCount" }
   ]
  },
  {
   "title": "Total SMS failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "smsFailureCount" }
   ]
  },
  {
   "title": "Total Calls",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "callCount" }
   ]
  },
  {
   "title": "Total Push Notifications",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "PushNotificationCount" }
   ]
  },
  {
   "title": "Total APNS Failure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "PushNotificationFailureCount{PushNotificationFailure=\"APNSPushNotificationFailureCount\"}"
    }
   ]
  },
  {
   "title": "Total FCM Failures",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "PushNotificationFailureCount{PushNotificationFailure=\"PushNotificationFailureCount\"}"
    }
   ]
  },
  {
   "title": "Total Calls Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "callFailureCount" }
   ]
  },
  {
   "title": "Total Socket Calls",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "socketCallCount" }
   ]
  },
  {
   "title": "Notification Pending Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "notificationPendingCount" }
   ]
  },
  {
   "title": "Notification Success  Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "notificationSuccessCount" }
   ]
  },
  {
   "title": "Total Notification Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "notificationFailureCount", "legendFormat": "notificationFailureCount" }
   ]
  },
  {
   "title": "Incoming Notification Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "incomingNotificationCount" }
   ]
  },
  {
   "title": "Total SMS sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "smsCount", "legendFormat": "{{smsCount}}" }
   ]
  },
  {
   "title": "SMS Failure Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "smsFailureCount" }
   ]
  },
  {
   "title": "Email Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "emailCount" }
   ]
  },
  {
   "title": "Email Failure Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "emailFailureCount" }
   ]
  },
  {
   "title": "Total Calls Made",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "callCount" }
   ]
  },
  {
   "title": "Calls Failure Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "callFailureCount" }
   ]
  },
  {
   "title": "Push Notification Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "PushNotificationCount", "legendFormat": "PushNotificationCount" }
   ]
  },
  {
   "title": "Push Notification Failure Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "PushNotificationFailureCount", "legendFormat": "PushNotificationFailureCount" }
   ]
  },
  {
   "title": "Socket Call Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "socketCallCount" }
   ]
  },
  {
   "title": "Push To Webhook Count Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pushToWebhookCounter", "legendFormat": "PushNotificationCount" }
   ]
  },
  {
   "title": "Total Push To Webhook Count Failure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pushToWebhookFailureCounter", "legendFormat": "PushNotificationFailureCount" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes / 1000000) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}